### ISSUE TITLE
Refactor Chirp.CLI's Program.cs. print statements ito own its own class

### ISSUE THREAD

**Issue by MRollin03** [ITU-BDSA2024-GROUP29/Chirp#1]
Refactor all print concerned code into its own class, something like `UserInterface`

Acceptence criteria
- code needs same basic functionalitet
- printstatements are isolated into seperate class

**Comment by yeeerdley-itu** [comment]
Work work 
![image](https://github.com/user-attachments/assets/38425464-06ef-4265-b3de-e50bda33b6f7)

**Comment by yeeerdley-itu** [comment]
har pushet, men det virker fjollet at ændre mere. Enig?
