### ISSUE TITLE
As a developer I would like to add a secondary login method through Oauth via Github

### ISSUE THREAD

**Issue by yeeerdley-itu** [ITU-BDSA2024-GROUP29/Chirp#59]
Issue #58 should be completed before initializing this

**Comment by yeeerdley-itu** [comment]
@MRollin03 if this is complete, just move it to finished the 'done' section, I will leave it for you here until then since i know you worked on this

**Comment by MRollin03** [comment]
Thank you forgot to mark this as done I will do it here and now.
Github OAuth usage of User-Secrets has been fixed with [Issue](https://github.com/ITU-BDSA2024-GROUP29/Chirp/pull/80#event-15365051191)
